### PR TITLE
fix:Failed to load b3dm model with error code 404

### PR DESCRIPTION
**Pull request by familyaa**
Provided ionAccessToken and ionAssetId as tests.

### CODE REVIEW

**Comment by familyaa** [comment]
before:
image
now:
image

**Comment by gkjohnson** [comment]
Hello @familyaa! Thanks for the suggested fix. Did the Cesium Ion API change? Do you have any referenced to documentation on how to consume Cesium Ion urls? This example used to work with a the originally provided asset id and public cesium ion access token.

**Comment by familyaa** [comment]
hello @gkjohnson 
I didn't find any description about the api change in the cesium ion api documentation, but found through the cesium sandcastle example that assetId is required when accessing the tiled data. 
You can see
https://cesium.com/learn/ion/rest-api/#operation/getAssetEndpoint
and
https://sandcastle.cesium.com/?src=3D%20Tiles%20Photogrammetry.html

**Comment by gkjohnson** [comment]
It looks like this has been caused by #256. I've proposed a fix in #262

**Comment by gkjohnson** [comment]
@familyaa with #262 merged can you give this another try

**Comment by familyaa** [comment]
@gkjohnson 
Great, the demo is working fine.

**Pull request closed without merging**
